[2024-11-21T06:01:07.248+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T06:01:07.271+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: countries_pipeline.print manual__2024-11-21T06:00:56.163901+00:00 [queued]>
[2024-11-21T06:01:07.284+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: countries_pipeline.print manual__2024-11-21T06:00:56.163901+00:00 [queued]>
[2024-11-21T06:01:07.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T06:01:07.305+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): print> on 2024-11-21 06:00:56.163901+00:00
[2024-11-21T06:01:07.314+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T06:01:07.316+0000] {standard_task_runner.py:72} INFO - Started process 164 to run task
[2024-11-21T06:01:07.317+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'countries_pipeline', 'print', 'manual__2024-11-21T06:00:56.163901+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/paises_api.py', '--cfg-path', '/tmp/tmpbgpbwztp']
[2024-11-21T06:01:07.318+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask print
[2024-11-21T06:01:07.608+0000] {task_command.py:467} INFO - Running <TaskInstance: countries_pipeline.print manual__2024-11-21T06:00:56.163901+00:00 [running]> on host bf751b86ec1d
[2024-11-21T06:01:07.719+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='countries_pipeline' AIRFLOW_CTX_TASK_ID='print' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T06:00:56.163901+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T06:00:56.163901+00:00'
[2024-11-21T06:01:07.721+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T06:01:07.722+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T06:01:07.723+0000] {logging_mixin.py:190} INFO - Current task name:print state:running start_date:2024-11-21 06:01:07.272925+00:00
[2024-11-21T06:01:07.724+0000] {logging_mixin.py:190} INFO - Dag name:countries_pipeline and current dag run status:running
[2024-11-21T06:01:07.725+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T06:01:07.727+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-21T06:01:07.728+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo [{"nome_comum":"Italy","population":59554023,"area":301336.0,"region":"Europe","densidade_populacional":197.6332831125},{"nome_comum":"Indonesia","population":273523621,"area":1904569.0,"region":"Asia","densidade_populacional":143.614445578},{"nome_comum":"South Africa","population":59308690,"area":1221037.0,"region":"Africa","densidade_populacional":48.5723937931},{"nome_comum":"France","population":67391582,"area":551695.0,"region":"Europe","densidade_populacional":122.1536936169},{"nome_comum":"Mexico","population":128932753,"area":1964375.0,"region":"Americas","densidade_populacional":65.6355090041},{"nome_comum":"China","population":1402112000,"area":9706961.0,"region":"Asia","densidade_populacional":144.4439717024},{"nome_comum":"Egypt","population":102334403,"area":1002450.0,"region":"Africa","densidade_populacional":102.0842964736},{"nome_comum":"Bangladesh","population":164689383,"area":147570.0,"region":"Asia","densidade_populacional":1116.0085586501},{"nome_comum":"Turkey","population":84339067,"area":783562.0,"region":"Asia","densidade_populacional":107.6354736447},{"nome_comum":"United Kingdom","population":67215293,"area":242900.0,"region":"Europe","densidade_populacional":276.7200205846},{"nome_comum":"Colombia","population":50882884,"area":1141748.0,"region":"Americas","densidade_populacional":44.5657745842},{"nome_comum":"Pakistan","population":220892331,"area":881912.0,"region":"Asia","densidade_populacional":250.469809913},{"nome_comum":"India","population":1380004385,"area":3287590.0,"region":"Asia","densidade_populacional":419.761705383},{"nome_comum":"Germany","population":83240525,"area":357114.0,"region":"Europe","densidade_populacional":233.0923038582},{"nome_comum":"Russia","population":144104080,"area":17098242.0,"region":"Europe","densidade_populacional":8.4280056394},{"nome_comum":"Ethiopia","population":114963583,"area":1104300.0,"region":"Africa","densidade_populacional":104.1053907453},{"nome_comum":"Thailand","population":69799978,"area":513120.0,"region":"Asia","densidade_populacional":136.0305152791},{"nome_comum":"Philippines","population":109581085,"area":342353.0,"region":"Asia","densidade_populacional":320.0821520477},{"nome_comum":"DR Congo","population":108407721,"area":2344858.0,"region":"Africa","densidade_populacional":46.2321048865},{"nome_comum":"Kenya","population":53771300,"area":580367.0,"region":"Africa","densidade_populacional":92.6505125205},{"nome_comum":"Vietnam","population":97338583,"area":331212.0,"region":"Asia","densidade_populacional":293.886039757},{"nome_comum":"Tanzania","population":59734213,"area":945087.0,"region":"Africa","densidade_populacional":63.2049885354},{"nome_comum":"South Korea","population":51780579,"area":100210.0,"region":"Asia","densidade_populacional":516.7206765792},{"nome_comum":"Japan","population":125836021,"area":377930.0,"region":"Asia","densidade_populacional":332.9611859339},{"nome_comum":"United States","population":329484123,"area":9372610.0,"region":"Americas","densidade_populacional":35.1539350298},{"nome_comum":"Nigeria","population":206139587,"area":923768.0,"region":"Africa","densidade_populacional":223.1508203358},{"nome_comum":"Iran","population":83992953,"area":1648195.0,"region":"Asia","densidade_populacional":50.9605677726},{"nome_comum":"Brazil","population":212559409,"area":8515767.0,"region":"Americas","densidade_populacional":24.9606886849},{"nome_comum":"Myanmar","population":54409794,"area":676578.0,"region":"Asia","densidade_populacional":80.4191002368}]']
[2024-11-21T06:01:07.741+0000] {subprocess.py:99} INFO - Output:
[2024-11-21T06:01:48.861+0000] {subprocess.py:110} INFO - Command exited with return code -9
[2024-11-21T06:01:50.362+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2024-11-21T06:01:50.588+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T06:01:50.590+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 06:01:07.272925+00:00 end:2024-11-21 06:01:50.497243+00:00 duration:43.224318
[2024-11-21T06:01:50.602+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): print> dag:<DAG: countries_pipeline> dagrun:<DagRun countries_pipeline @ 2024-11-21 06:00:56.163901+00:00: manual__2024-11-21T06:00:56.163901+00:00, state:running, queued_at: 2024-11-21 06:00:56.187919+00:00. externally triggered: True>
[2024-11-21T06:01:50.605+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code -9.
[2024-11-21T06:01:50.609+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=countries_pipeline, task_id=print, run_id=manual__2024-11-21T06:00:56.163901+00:00, execution_date=20241121T060056, start_date=20241121T060107, end_date=20241121T060150
[2024-11-21T06:01:51.015+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T06:01:51.039+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 60 for task print (Bash command failed. The command returned a non-zero exit code -9.; 164)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2024-11-21T06:01:51.191+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-21T06:01:51.506+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T06:01:51.511+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
